---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 650
    exclude_paths:
      - "**/tests"
  eslint:
    enabled: true
    channel: "eslint-2"
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.es6"
  - "**.module"
exclude_paths:
- "bin/**/*"
- "test/**/*"
- "**/tests"
- "tmp/**/*"
- "vendor/**/*"
- "coverage/*"
- "**/coverage"
- ".idea/"
- "**.spec.js"
- "**.min.js"
- "**.min.css"
- "**/dist"
- "**/node_modules"
- "**/packages"
