language: node_js
sudo: false
node_js:
  - '0.12'
cache:
  directories:
    - $(npm root -g)
notifications:
  email:
    - devs-deep@mitocgroup.com
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    #CODACY_PROJECT_TOKEN =[secured]
    - secure: XkXoUfGvUcl+UwoqhEZ/2JO4s2oHCBDcBg8k1sxNvqzLj6M6Fa/cd0JFWkyzGaT1aB14A1O9S2Aa6F0z4nExp3USUC9HJew6WjH3Mwzf0o4fvoL1GNcL0+Ybp1ZBJauSepNhsNeEUNyZGEnaoxqERl091XcEA7gqStG1jPWZ5SmJo8F3u7M3HyKiNYRlNltctR9WM30qV8pvoKvq89trTTT/XhWXjV8Y2VuDzri6GYKLcf6F4KtHhFWiRsw0Mzke/OVv1pVfpBYul4sut0gdTYOOdtY4FG+qfBDNP1NNTRVPpnybxuB1H8fudNFq4kmyggfef3rRUk/Q17Y9AQzUOg76HwiUGWCpwadE9yxgTkwii1uGfKq1CF9G9+riGszyMninR6VTespjwd1Ayq9AvW3iERu0ywVqAMdne2HRuHYcWpiadUt0rJfAScGhIh7L+NIM3hagxX4CL8MB8pplKM/6Ty+/4NVJ8Ybc2UQz/f27RKgTBYdSY+QrRPbcekyIgNnVceY/JwCuPF1bRgBnICLjFACjBasjeqbCavB0M8NCqqHjT86cSLMDEONjtXoH4Yd/S0BDwJ6Wgn0Z+LA03+VVJKTBGwqmdUropWChIhRTmnpWbw5fNg+jFq5bb/Qr21iEEEhGFG7DgDqfP4upDMimuXKUztHM0uscAinoDTw=
before_install:
  - npm install -g babel-cli
  - npm install -g browserify@11.2.0
  - npm install -g mocha@2.3.3
  - npm install -g mocha-babel@3.0.0
  - npm install -g istanbul@0.3.21
  - npm install -g istanbul-combine@0.3.0
  - npm install -g codacy-coverage@1.1.3
  - cp test/package.json .
after_success:
  - npm run coverage
