language: node_js
sudo: false
node_js:
- '0.12'
cache:
  directories:
  - $(npm root -g)
notifications:
  email:
  - devs-deep@mitocgroup.com
branches:
  only:
  - master
  - stage
  - test
  - dev
env:
  global:
  #COVERALLS_SERVICE_NAME =[secured]
  - secure: MHn3FJiEdvawFmTfSUp/UJaJRcL1L5yUY3JBQgQCd4h+oZTC6vNNpLnbOfhu5TEbwhiryc0XHXAYJ8a96tA6nqa+ejcUASeSaDyjAZH/QsZpGJ+x45n5S2Zcf/gaxnJGkEr+gU5jYTHU4khai8guWlYBQw/tn7kcjoSXb5dphZbXSfcKj7sxb4DEd9yYM/1D0UBwgJDboGtXOdz/yEFXRcPyZlLb38X0xmhCQUGtuZtFbxBCZLilVenOUBhA2m0aylOk6+ueVylc2/n5EsEBPQ3e4Dqywje5/i6SM9jee9uIO/umimab+WocK9UwTN+g7/VAb6QpHGoY0MFbzLoeOebfaA1LSkFU2txqEuOip8NCrpZqNFtRqVDjQs7MDCEF5gAgc2V/zYJyFrEkjngIpWGiNKlJlHQ1L/aQFuyecOL6VpBNtwLB6GNZ7iVUKDKx+yKVsZMa8TezUy8k0NA/Cu8WjhylWVmkQnQV7wj82REPl/NKR2MIpRl1pgFJg5WcAQahKvFQxIywkMqvNDM08IZ2QfdXJemCaIhl9PbISgRpoCkUfCI5Bc/47U4W3OFoYDEUyNuNuUktXMAh65feBT9ypjylN1qNadsiro0HSPZF2UytWx5rKLDUfFdq8bN9dgV8FWuFglsMdPjD6DNlSD1N8Y/nU0v9gK/868m+Qe8=
  #COVERALLS_REPO_TOKEN =[secured]
  - secure: cI5HShveGCsAwdNZ6ghnBOmxICECeyTk6lLaOd3Tv+MpzIhXAyXOVb+42eE01Nz2FGJbviOyXOX1D8ugCiZDGLrMp8VEUGy+kClWzrlpIOQLLlqaOng6WMobVzq4mU6S/LazqGUNyfvh/mEsMI6JVtaoLEObfLPFP7xJCteUy4T2u33iTH9cvn538rNoxRK37Fck7FWeCj5bm6TcNhqDFmrds02Scqhb/VdxI88KAWkmMvCcIDIr6r4vu20HlewKtByI0p8j7XH4l3++P7XykUcxK/4UIf9c2HckoUgJgnj7BmO8vKDyZtqoC3ovt+nEgGOuxY1CQgf2+s6PKaRQpGsW1apZToIcsibC48L2FWjEm1eOyCHR4R+zz3bPYWiS+alE0uSN2StsX+xulhE9KKAqsw606mCDjlQUvFtXWWRAkaxiAy7S1bzVa0E6URXDZl/Poa9jBXtN68hqozIUTs2QUAqAat3u8tOvYeV5A/B/XmQMqJJTNNNrzAJNUGXvnj3hDp6Yyqcs+GJKb4f/89ljD7d/lfjn0R/RXhduGu8aL+0QocZeOuptK6LoOjmfSdhmOaCCYHdrGGbDiV1fHyUS6DTfVgweHCjM6TiaCY5ERmLX+fdtg+JZUBakoUFH8z1h+b0u0b9RCxuariUpq7jWf2UA3vORYq118LhqlKo=
  #CODACY_PROJECT_TOKEN =[secured]
  - secure: FwXnAYWmzrHaCxpXZWD3XjOpwXmW8+Yq5r7//A7LsYSCSYiok6N6BUNgUfzAj5+As0MC9Cyweohc4H9wqgq8To+wbp0Cai0LlrTQUZ08I8vPkEkD4yv6N+3K2vElwyUGx772SRR+p/SkqX7O5B2ScRedhGOMx4FhdjZY6hHQfNjIh72poIAJ7qQ7vP/rPQCBWK5ts/jTGINBycQYV+t3THVrxYVTx+BiGgzC5jGIlchsOQyAGQa+GR5QDw27wU2WirCjpRsq/86snQw48UeN6J+8FXkbgQXp5CZc5R4pjybQpSQDv5mxDJV7HirxlK/DbVB1GuFDV6upA4TX5WNyPqUYUMAvAXAcSExj3FmJUk99rGPJ9Euzks+9wgR/OOGlO5F/kPRM3BebT+tqDVHffp07mKJ2Sq3FqOoQQDAjp1wyqY0N5uE2JPQ6GJQ0PIkm26jOzWaQllC7Ib6j03iBG4hKFJK8wYZn1nkk+tFUVWdT4uG6tGIIdkZjlMRngnCoi0FfKV6Vd89HMdnpzygRLwITizhfZ+EHljuphGbMIWLBhIei+GndVLysL+tpI+tBVgHcHT2F2XJTwvSZqWrWqkDQVzZEqjF4P03pKmdt5c4P2zSN8UL4eFqRYids9FsKG18qjmj74BujHa+tL2+dLrWWpOH2SXNRt0vy+rHdvss=
before_install:
- npm install -g babel
- npm install -g browserify
- npm install -g mocha
- npm install -g mocha-babel
- npm install -g istanbul
- npm install -g coveralls
- npm install -g codacy-coverage
- npm install -g istanbul-combine
- cp test/package.json .
- test/bin/setup_npm.sh
after_success:
- npm run coverage
