language: node_js
sudo: false
node_js:
  - '4.3'
  - '5.11'
  - '6.2'
cache:
  directories:
    - $(npm root -g)
    - node_modules
    - $(npm config get prefix)/bin
notifications:
  email:
    - devs-deep@mitocgroup.com
  slack:
    secure: Kv3toHMK+/TguJa9jIbIhii/XmLZUDlEX8YiDSJv1S6zKEQqowqXT2Gi1J9u8KYiZBQC+S3x+T9eRkkNJk7RMrLaotbrtI5DNa7ynrhSydIApZIXxISZBh4Ihbdsch7y6ZPDuaGATKSInKY96NRqbXozw9f/pNYc/c2nq3BIBBexLAfGNlQPgVqBNKw12WlfU8O1ARMpQ3fWDE1JgTtLYZst1EGXwkm87O5ybDUcEUY+qqwj6I5HYSpCjanZ3ILeYagrb79gbgU6llusI6YF4PKVH12+51O0xqpvqawxqcLWbKwv7Y1H8kUBI0vKSPlvLS9dsqwnjG8BpHse2ypSzqfuMyViETmpP+ZHFJ8avxrGsPdiQe4doqiYBz2dkxRyorx4QTI/5JP/CGIp9k7NCsd3KQGViHvWOqMnYyBzkd8bTvYNbJYQ72xOYrgAhsiqEJaCOUk4x8h4pSUBb/r021XK3uIU9hu1GXdLg5o57pFk3XNFzD9pUBsQi6TZLYwH8GFGcJEUbDEYA8Gev5E/ZDRz3IheFL7oIWZbssT8I3uXojMMMQvBf4masC8MmYhc8IQh3LCS8h78Sw07sFEhcjXMcNCxeM+B5lkoByiLBMuI2Jwvfo/C2ulqitwo4niqju45bh/rsdUlJEJZwTrDkpj0imjDHQPxhSo9Ftrqk68=
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
  - secure: HLO6+HNsn5INLhN2VvLTKL64OGcBEWEjGKjfMY0cIaX0LlubLYtjKdP1YZpFlSDaeDwiPBSzzYdihwgA2y+FzSZUPgy3Z1UrwHGYsT1e/NhHGg7pjO0qVwogskR/0ieh7EDroK+6YndCujduPQDoXRcYOtSOU+iq12zwsY/H53VTLR3ZJw+9EWU+VvvnzMPXFFwSt0eVljzZacq2E4UWtbEdGYNdzzOKEZdP/eJPubuCGdbO+F1ae6jjzpaxwj1fKoOKoqh8CXZsjyJkGJJG7/3MwaA9ZJnhnoUoH1HlwqESlCWqV5zm4niN1SScOOiGmnirNFbMHrZcPN8qVsQMpNM9fqCpuDZjVZjALTGdK/l3wT34TEIx54MVIs6SfKs5d3q8TFScqZgUtEsv9SUQs13GmazncpxkB3/OJ/yYUjyT7CRC2b9RDVS8fYhuwytuX8woRNscm3EfgiT6bc0py/ppR5djt019AUjsS7lN3DDiTqkRKp6vD0mJw0Bu3Nibjl9uP2u+THMywrhI9IjyK/8GlY0WePE9G5d+7jb3Gq7SC+JEV6O6mMGl4sAfx+RRmL9yRZoXeCWKVTrCn5+BNikBouCFCAmxUPs8QizOzKz8H4RrGR3EYungvriAcke3j9I5MBEETr14xeo4oXhVQEmh8w6QBmCYFRNPQkqPHwc=
before_install:
  - (npm list -g babel-cli --depth=0 || npm install -g babel-cli@6.x.x)
  - (npm list -g babel-polyfill --depth=0 || npm install -g babel-polyfill)
  - (npm list -g babel-preset-es2015 --depth=0 || npm install -g babel-preset-es2015)
  - (npm list -g babel-plugin-add-module-exports --depth=0 || npm install -g babel-plugin-add-module-exports)
  - (npm list -g browserify --depth=0 || npm install -g browserify@11.2.x)
  - (npm list -g mocha --depth=0 || npm install -g mocha@2.4.x)
  - (npm list -g istanbul@^1.0.0-alpha --depth=0 || npm install -g istanbul@^1.0.0-alpha)
  - (npm list -g codacy-coverage --depth=0 || npm install -g codacy-coverage@1.1.x)
  - cp test/package.json .
after_success:
  - npm run coverage
